/*
80/20 rule. It is said that 80% of the calls are generated by 20% of the callers. Is this true? What percentage of calls are generated by the most active 20% of callers.

 - what are the most active 20%?

1. Number of calls per user
2. Get number of users
3. Filter the top X users
4. Sum the calls from these users / total calls

*/

WITH user_calls AS (
    SELECT
        Caller_id,
        COUNT(*) AS Number_calls
    FROM
        Issue
    GROUP BY
        1
    ORDER BY
        2 DESC
), ranked_users AS (
    SELECT
        *,
        RANK() OVER (ORDER BY Number_calls DESC) AS Caller_rank
    FROM user_calls
), total_metrics AS (
    SELECT
        COUNT(Caller_id) AS total_users,
        SUM(Number_calls) AS total_calls
    FROM
        ranked_users
), 
twenty_metrics AS (
    SELECT
        COUNT(Caller_id) AS total_users,
        SUM(Number_calls) AS total_calls
    FROM
        ranked_users
    WHERE
        Caller_rank <= FLOOR((SELECT MAX(Caller_rank) / 5 FROM ranked_users))
)

SELECT
    twenty_metrics.total_calls / total_metrics.total_calls * 100 AS t20pc
FROM
    total_metrics CROSS JOIN twenty_metrics